package BancoModule;


/**
* BancoModule/BancoPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banco.idl
* miércoles 16 de octubre de 2024 08:47:57 PM CDT
*/

public abstract class BancoPOA extends org.omg.PortableServer.Servant
 implements BancoModule.BancoOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("depositar", new java.lang.Integer (0));
    _methods.put ("retirar", new java.lang.Integer (1));
    _methods.put ("consultarSaldo", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // BancoModule/Banco/depositar
       {
         double cantidad = in.read_double ();
         this.depositar (cantidad);
         out = $rh.createReply();
         break;
       }

       case 1:  // BancoModule/Banco/retirar
       {
         double cantidad = in.read_double ();
         this.retirar (cantidad);
         out = $rh.createReply();
         break;
       }

       case 2:  // BancoModule/Banco/consultarSaldo
       {
         double $result = (double)0;
         $result = this.consultarSaldo ();
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:BancoModule/Banco:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Banco _this() 
  {
    return BancoHelper.narrow(
    super._this_object());
  }

  public Banco _this(org.omg.CORBA.ORB orb) 
  {
    return BancoHelper.narrow(
    super._this_object(orb));
  }


} // class BancoPOA
