package BancoModule;


/**
* BancoModule/BancoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banco.idl
* miércoles 16 de octubre de 2024 08:47:57 PM CDT
*/

public interface BancoOperations 
{
  void depositar (double cantidad);
  void retirar (double cantidad);
  double consultarSaldo ();
} // interface BancoOperations
