package BancoModule;

/**
* BancoModule/BancoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banco.idl
* miércoles 16 de octubre de 2024 08:47:57 PM CDT
*/

public final class BancoHolder implements org.omg.CORBA.portable.Streamable
{
  public BancoModule.Banco value = null;

  public BancoHolder ()
  {
  }

  public BancoHolder (BancoModule.Banco initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BancoModule.BancoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BancoModule.BancoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BancoModule.BancoHelper.type ();
  }

}
