package BancoModule;


/**
* BancoModule/Banco.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banco.idl
* miércoles 16 de octubre de 2024 08:47:57 PM CDT
*/

public interface Banco extends BancoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Banco
