package FibonacciModule;


/**
* FibonacciModule/FibonacciOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from fibonacci.idl
* sábado 19 de octubre de 2024 05:45:52 PM CDT
*/

public interface FibonacciOperations 
{
  int fibonacci (int n);
} // interface FibonacciOperations
