package FibonacciModule;


/**
* FibonacciModule/Fibonacci.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from fibonacci.idl
* sábado 19 de octubre de 2024 05:45:52 PM CDT
*/

public interface Fibonacci extends FibonacciOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Fibonacci
