package FibonacciModule;

/**
* FibonacciModule/FibonacciHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from fibonacci.idl
* sábado 19 de octubre de 2024 05:45:52 PM CDT
*/

public final class FibonacciHolder implements org.omg.CORBA.portable.Streamable
{
  public FibonacciModule.Fibonacci value = null;

  public FibonacciHolder ()
  {
  }

  public FibonacciHolder (FibonacciModule.Fibonacci initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FibonacciModule.FibonacciHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FibonacciModule.FibonacciHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FibonacciModule.FibonacciHelper.type ();
  }

}
