package FibonacciModule;


/**
* FibonacciModule/FibonacciPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from fibonacci.idl
* sábado 19 de octubre de 2024 05:45:52 PM CDT
*/

public abstract class FibonacciPOA extends org.omg.PortableServer.Servant
 implements FibonacciModule.FibonacciOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("fibonacci", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // FibonacciModule/Fibonacci/fibonacci
       {
         int n = in.read_long ();
         int $result = (int)0;
         $result = this.fibonacci (n);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:FibonacciModule/Fibonacci:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Fibonacci _this() 
  {
    return FibonacciHelper.narrow(
    super._this_object());
  }

  public Fibonacci _this(org.omg.CORBA.ORB orb) 
  {
    return FibonacciHelper.narrow(
    super._this_object(orb));
  }


} // class FibonacciPOA
