package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* miércoles 16 de octubre de 2024 08:11:11 PM CDT
*/

public interface HelloOperations 
{
  String sayHello ();
} // interface HelloOperations
